# Generated by Django 2.0.13 on 2019-03-14 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='curtomer_ip',
            new_name='customer_ip',
        ),
    ]
