# Generated by Django 2.0.13 on 2019-04-02 11:07

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190314_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notify_url',
            field=models.URLField(default=products.models.notify_url_default),
        ),
    ]
